### ISSUE TITLE
Add Topbar UX/UI

### ISSUE THREAD

**Issue by CharlieGreenman** [razroo/employee-dashboard-angular#1]
https://www.figma.com/community/file/981222492650063115?preview=fullscreen

<img width="1059" alt="Screen Shot 2021-06-02 at 2 07 21 AM" src="https://user-images.githubusercontent.com/8540141/120400863-69335c00-c347-11eb-8208-490bf6ce8e49.png">

This includes:
1. Avatar Icon
2. Question Mark
3. Notification Bell 

No need for a dropdown. We will be using font-awesome free version for icons.

**Comment by tommymaher15** [comment]
Oddly enough the problem I was having with MD not being known

Disappeared and I didn't change the markup on the module. 

Interesting..

**Comment by tommymaher15** [comment]
I think everything here should be fine. 

The errors I was battling weren't affecting the anything on the site but looks ok for now I hope! 


Will finish off the last of the sidebar functionality now and write an issue maybe for implementing some other stuff over the weekend.
